lib/nfl_rushing_web/router.ex
defmodule NflRushingWeb.Router do
  use NflRushingWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {NflRushingWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NflRushingWeb do
    pipe_through :browser

    live "/", StatsLive, :index
    get("/csv", CSVController, :export)
  end

  # Other scopes may use custom stacks.
  # scope "/api", NflRushingWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NflRushingWeb.Telemetry
    end
  end
end

lib/nfl_rushing_web/live/stats_live.ex
defmodule NflRushingWeb.StatsLive do
  use NflRushingWeb, :live_view

  alias NflRushing.RushingStats

  @impl true
  @spec render(Phoenix.LiveView.Socket.assigns()) :: Phoenix.LiveView.Rendered.t()
  def render(assigns) do
    Phoenix.View.render(NflRushingWeb.StatsView, "index.html", assigns)
  end

  @impl true
  @spec mount(
          Phoenix.LiveView.unsigned_params() | :not_mounted_at_router,
          map(),
          Phoenix.LiveView.Socket.t()
        ) ::
          {:ok, Phoenix.LiveView.Socket.t()}
  def mount(_params, _session, socket) do
    %{
      paginated_rushing_stats: rushing_stats,
      pagination: pagination,
      sort_by: sort_by,
      player: player
    } = RushingStats.get_rushing_stats(1, nil, "")

    {:ok,
     assign(socket,
       rushing_stats: rushing_stats,
       pagination: pagination,
       sort_by: sort_by,
       player: player
     )}
  end

  @impl true
  @spec handle_event(binary(), Phoenix.LiveView.unsigned_params(), Phoenix.LiveView.Socket.t()) ::
          {:noreply, Phoenix.LiveView.Socket.t()}
  def handle_event("pagination", %{"page" => page}, socket) do
    {page_number, _} = Integer.parse(page)

    %{
      paginated_rushing_stats: rushing_stats,
      pagination: pagination,
      sort_by: sort_by,
      player: player
    } = RushingStats.get_rushing_stats(page_number, socket.assigns.sort_by, socket.assigns.player)

    {:noreply,
     assign(socket,
       rushing_stats: rushing_stats,
       pagination: pagination,
       sort_by: sort_by,
       player: player
     )}
  end

  def handle_event("sort", %{"sort_by" => sort_by_param}, socket) do
    if sort_by_param == socket.assigns.sort_by do
      {:noreply, socket}
    else
      %{
        paginated_rushing_stats: rushing_stats,
        pagination: pagination,
        sort_by: sort_by,
        player: player
      } = RushingStats.get_rushing_stats(1, sort_by_param, socket.assigns.player)

      {:noreply,
       assign(socket,
         rushing_stats: rushing_stats,
         pagination: pagination,
         sort_by: sort_by,
         player: player
       )}
    end
  end

  def handle_event("search", %{"search" => %{"player" => player_param}}, socket) do
    %{
      paginated_rushing_stats: rushing_stats,
      pagination: pagination,
      sort_by: sort_by,
      player: player
    } = RushingStats.get_rushing_stats(1, socket.assigns.sort_by, player_param)

    {:noreply,
     assign(socket,
       rushing_stats: rushing_stats,
       pagination: pagination,
       sort_by: sort_by,
       player: player
     )}
  end

  def handle_event("maybe_clear_search", %{"search" => %{"player" => ""}}, socket) do
    %{
      paginated_rushing_stats: rushing_stats,
      pagination: pagination,
      sort_by: sort_by,
      player: player
    } = RushingStats.get_rushing_stats(1, socket.assigns.sort_by, "")

    {:noreply,
     assign(socket,
       rushing_stats: rushing_stats,
       pagination: pagination,
       sort_by: sort_by,
       player: player
     )}
  end

  def handle_event("maybe_clear_search", _session, socket), do: {:noreply, socket}
end

lib/nfl_rushing_web/views/stats_view.ex
defmodule NflRushingWeb.StatsView do
  use NflRushingWeb, :view

  @spec pagination_numbers(integer(), integer()) :: list()
  def pagination_numbers(current_page, total_pages) do
    initial_number = calc_initial_page_number(current_page, total_pages)
    last_number = calc_last_page_number(current_page, total_pages)

    Enum.to_list(initial_number..last_number)
  end

  defp calc_initial_page_number(current_page, _total_pages) when current_page <= 3, do: 1

  defp calc_initial_page_number(current_page, _total_pages), do: current_page - 3

  defp calc_last_page_number(current_page, total_pages) when current_page == total_pages,
    do: total_pages

  defp calc_last_page_number(current_page, total_pages) when total_pages - current_page <= 3,
    do: total_pages

  defp calc_last_page_number(current_page, _total_pages), do: current_page + 3
end

lib/nfl_rushing_web/templates/stats/_filters.html.leex
<div class="row" style="margin-bottom: 0">
  <div class="col s6">
    <%= render "_search_form.html", assigns %>
  </div>
  <div class="col s6">
    <div class="right">
      <a class='dropdown-trigger btn mt' href='#' data-target='sort-by'> Sort By <i class="material-icons" style="line-height: 1;">arrow_drop_down</i></a>
      <%= link "EXPORT CSV", to: Routes.csv_path(@socket, :export, sort: @sort_by, player: @player), class: "waves-effect waves-light btn mt" %>

      <ul id='sort-by' class='dropdown-content'>
        <li><a href="#!" phx-click="sort" phx-value-sort_by="asc_yds">ASC Total Rushing Yards</a></li>
        <li><a href="#!" phx-click="sort" phx-value-sort_by="desc_yds">DESC Total Rushing Yards</a></li>
        <li class="divider" tabindex="-1"></li>
        <li><a href="#!" phx-click="sort" phx-value-sort_by="asc_td">ASC Total Rushing Touchdowns</a></li>
        <li><a href="#!" phx-click="sort" phx-value-sort_by="desc_td">DESC Total Rushing Touchdowns</a></li>
        <li class="divider" tabindex="-1"></li>
        <li><a href="#!" phx-click="sort" phx-value-sort_by="asc_lng">ASC Longest Rush</a></li>
        <li><a href="#!" phx-click="sort" phx-value-sort_by="desc_lng">DESC Longest Rush</a></li>
      </ul>
    </div>
  </div>
</div>

lib/nfl_rushing_web/templates/stats/_pagination.html.leex
<ul class="pagination">
  <%= if @pagination.page_number > 1 do %>
    <li class="waves-effect"><a href="#" phx-click="pagination" phx-value-page="1"><i class="material-icons">first_page</i></a></li>
    <li class="waves-effect"><a href="#" phx-click="pagination" phx-value-page="<%= @pagination.page_number - 1 %>"><i class="material-icons">chevron_left</i></a></li>
  <% end %>
  <%= for idx <- pagination_numbers(@pagination.page_number, @pagination.total_pages) do %>
    <li class="<%= if @pagination.page_number == idx, do: "active" %>">
      <a href="#" phx-click="pagination" phx-value-page="<%= idx %>"><%= idx %></a>
    </li>
  <% end %>
  <%= if @pagination.page_number < @pagination.total_pages do %>
    <li class="waves-effect"><a href="#" phx-click="pagination" phx-value-page="<%= @pagination.page_number + 1 %>"><i class="material-icons">chevron_right</i></a></li>
    <li class="waves-effect"><a href="#" phx-click="pagination" phx-value-page="<%= @pagination.total_pages %>"><i class="material-icons">last_page</i></a></li>
  <% end %>
</ul>

lib/nfl_rushing_web/templates/stats/_search_form.html.leex
<%= f = form_for :search, "#",
    [class: "col s12", phx_submit: :search, phx_change: "maybe_clear_search", onsubmit: "event.preventDefault();"] %>
  <div class="input-field inline">
    <%= label(f, :player, "player's name") %>
    <%= text_input f, :player, value: @player %>
  </div>
  <%= submit "search", class: "btn ml" %>
</form>

lib/nfl_rushing_web/templates/stats/_table.html.leex
 <table class="responsive-table striped">
  <thead>
    <tr>
        <th>Player</th>
        <th>Team</th>
        <th>Position</th>
        <th>Game Attempts Avg</th>
        <th>Total Attempts</th>
        <th>Total Rushing Yards</th>
        <th>Attempt avg yards</th>
        <th>Total Rushing Touchdowns</th>
        <th>Longest Rush</th>
        <th>game avg yards</th>
        <th>rushing first downs</th>
        <th>rushing first downs percentage</th>
        <th>rushing 20 plus</th>
        <th>rushing 40 plus</th>
        <th>rushing fumbles</th>
    </tr>
  </thead>
  <tbody>
    <%= for rushing_stat <- @rushing_stats do %>
      <tr>
        <td> <%= rushing_stat.player %> </td>
        <td> <%= rushing_stat.team %> </td>
        <td> <%= rushing_stat.position %> </td>
        <td> <%= rushing_stat.game_attempts_avg %> </td>
        <td> <%= rushing_stat.total_attempts %> </td>
        <td> <%= rushing_stat.total_yards %> </td>
        <td> <%= rushing_stat.attempt_avg_yards %> </td>
        <td> <%= rushing_stat.total_rushing_touchdowns %> </td>
        <td> <%= rushing_stat.longest_rush %> </td>
        <td> <%= rushing_stat.game_avg_yards %> </td>
        <td> <%= rushing_stat.rushing_first_downs %> </td>
        <td> <%= rushing_stat.rushing_first_downs_percentage %> </td>
        <td> <%= rushing_stat.rushing_20_plus %> </td>
        <td> <%= rushing_stat.rushing_40_plus %> </td>
        <td> <%= rushing_stat.rushing_fumbles %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/nfl_rushing_web/templates/stats/index.html.leex
<%= render "_filters.html", assigns %>

<%= render "_table.html", assigns %>

<%= render "_pagination.html", assigns %>